// apps/stories/stories/react/Droppable/MultipleDroppable/MultipleDroppableApp.tsx
import React, {useState} from 'react';
import {DragDropProvider, useDraggable, useDroppable} from '@dnd-kit/react';

function Draggable({id}: {id: string}) {
  const {ref} = useDraggable({id});

  return <button ref={ref} className="btn">draggable</button>;
}

function Droppable({id, children}: {id: string; children?: React.ReactNode}) {
  const {ref, isDropTarget} = useDroppable({id});

  return (
    <div ref={ref} className={isDropTarget ? "droppable active" : "droppable"}>
      {children}
    </div>
  );
}

export default function App() {
  const [parent, setParent] = useState<string | undefined>(undefined);
  const draggable = <Draggable id="draggable" />;
  const droppables = ['A', 'B', 'C'];

  return (
    <DragDropProvider
      onDragEnd={(event) => {
        if (event.canceled) return;
        setParent(event.operation.target?.id as string);
      }}
    >
      <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, maxWidth: 500, margin: '0 auto'}}>
        <div style={{display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
          {parent == null ? draggable : null}
        </div>
        {droppables.map((id) => (
          <Droppable key={id} id={id}>
            {parent === id ? draggable : null}
          </Droppable>
        ))}
      </div>
    </DragDropProvider>
  );
}

// apps/stories-vue/stories/Droppable/MultipleDroppable/MultipleDroppableApp.vue
<script setup lang="ts">
import {ref} from 'vue';
import {DragDropProvider} from '@dnd-kit/vue';

const parent = ref<string | undefined>(undefined);
const droppables = ['A', 'B', 'C'];

function onDragEnd(event: any) {
  if (event.canceled) return;
  parent.value = event.operation.target?.id;
}
</script>

<script lang="ts">
import {defineComponent} from 'vue';
import {useDraggable, useDroppable} from '@dnd-kit/vue';

const DraggableItem = defineComponent({
  setup() {
    const element = ref<HTMLElement | null>(null);
    useDraggable({id: 'draggable', element});
    return {element};
  },
  template: `<button ref="element" class="btn">draggable</button>`,
});

const DroppableZone = defineComponent({
  props: {
    id: {type: String, required: true},
  },
  setup(props) {
    const element = ref<HTMLElement | null>(null);
    const {isDropTarget} = useDroppable({id: props.id, element});
    return {element, isDropTarget};
  },
  template: `<div ref="element" :class="['droppable', isDropTarget && 'active']"><slot /></div>`,
});

export default defineComponent({components: {DraggableItem, DroppableZone}});
</script>

<template>
  <DragDropProvider @dragEnd="onDragEnd">
    <div :style="{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '20px', maxWidth: '500px', margin: '0 auto'}">
      <div :style="{display: 'flex', alignItems: 'center', justifyContent: 'center'}">
        <DraggableItem v-if="parent == null" />
      </div>
      <DroppableZone v-for="id in droppables" :key="id" :id="id">
        <DraggableItem v-if="parent === id" />
      </DroppableZone>
    </div>
  </DragDropProvider>
</template>
