// apps/templates/vue-sortable/src/SortableItem.vue
<script setup>
import { ref, computed } from 'vue';
import { useSortable } from '@dnd-kit/vue/sortable';

const props = defineProps(['id', 'index']);
const element = ref(null);
const { isDragging } = useSortable({
  id: computed(() => props.id),
  index: computed(() => props.index),
  element,
});
</script>

<template>
  <li ref="element" class="item">
    Item {{ id }}
  </li>
</template>

// apps/stories-svelte/stories/Sortable/SortableItem.svelte
<script lang="ts">
  import {createSortable} from '@dnd-kit/svelte/sortable';

  let {id, index}: {id: number; index: number} = $props();

  const sortable = createSortable({
    get id() { return id; },
    get index() { return index; },
  });
</script>

<li
  {@attach sortable.attach}
  class="item"
  data-shadow={sortable.isDragging ? 'true' : undefined}
>
  {id}
</li>
