// apps/stories-solid/components/Item/Item.tsx
import './Item.css';
import { JSX, splitProps, mergeProps } from 'solid-js';
import { Dynamic } from 'solid-js/web';

interface ItemProps extends JSX.HTMLAttributes<HTMLElement> {
  actions?: JSX.Element;
  accentColor?: string;
  shadow?: boolean;
  transitionId?: string;
  children?: JSX.Element;
  as?: 'div' | 'button';
  ref?: (el: HTMLElement) => void;
}

export function Item(props: ItemProps) {
  const [local, rest] = splitProps(props, [
    'accentColor',
    'shadow',
    'transitionId',
    'children',
    'as',
    'style',
    'ref',
  ]);
  
  const style = () => typeof local.style === 'object' && local.style !== null ? local.style : {};
  
  return (
    <Dynamic
      component={local.as || 'div'}
      class="Item"
      data-shadow={local.shadow}
      data-accent-color={local.accentColor}
      style={{
        ...style(),
        'view-transition-name': local.transitionId,
        '--accent-color': local.accentColor,
      }}
      ref={local.ref}
      {...rest}
    >
      {local.children}
    </Dynamic>
  );
}

// apps/docs/stories/react/components/Item/Item.tsx
import React, {
  forwardRef,
  type CSSProperties,
  type HTMLAttributes,
  type PropsWithChildren,
} from 'react';

export interface Props extends HTMLAttributes<HTMLElement> {
  actions?: React.ReactNode;
  accentColor?: string;
  shadow?: boolean;
  transitionId?: string;
}

export const Item = forwardRef<HTMLElement, PropsWithChildren<Props>>(
  function Button(
    {actions, accentColor, children, shadow, style, transitionId, ...props},
    ref
  ) {
    const Element = actions ? 'div' : 'button';

    return (
      <Element
        {...props}
        className={'Item'}
        style={
          {
            ...style,
            viewTransitionName: transitionId,
            '--accent-color': accentColor,
          } as CSSProperties
        }
        data-shadow={shadow}
        data-accent-color={accentColor}
        ref={ref as any}
      >
        {children}
        {actions}
      </Element>
    );
  }
);
