// apps/stories-vue/stories/Sortable/MultipleLists/SortableColumn.vue
<script setup lang="ts">
import {ref, computed} from 'vue';
import {CollisionPriority} from '@dnd-kit/abstract';
import {useSortable} from '@dnd-kit/vue/sortable';

import SortableItem from './SortableItem.vue';

const props = defineProps<{
  id: string;
  index: number;
  rows: string[];
  colors: Record<string, string>;
}>();

const element = ref<HTMLElement | null>(null);
const handle = ref<HTMLElement | null>(null);

const {isDragging} = useSortable({
  id: computed(() => props.id),
  index: computed(() => props.index),
  element,
  handle,
  accept: ['column', 'item'],
  collisionPriority: CollisionPriority.Low,
  type: 'column',
});
</script>

<template>
  <div
    ref="element"
    class="container"
    :data-shadow="isDragging ? 'true' : undefined"
  >
    <h2>
      {{ id }}
      <button ref="handle" class="handle" />
    </h2>
    <ul>
      <SortableItem
        v-for="(itemId, itemIndex) in rows"
        :key="itemId"
        :id="itemId"
        :column="id"
        :index="itemIndex"
        :accent-color="colors[id]"
      />
    </ul>
  </div>
</template>

// apps/stories-svelte/stories/Sortable/MultipleLists/SortableColumn.svelte
<script lang="ts">
  import {CollisionPriority} from '@dnd-kit/abstract';
  import {createSortable} from '@dnd-kit/svelte/sortable';

  import SortableItem from './SortableItem.svelte';

  let {
    id,
    index,
    rows,
    colors,
  }: {
    id: string;
    index: number;
    rows: string[];
    colors: Record<string, string>;
  } = $props();

  const sortable = createSortable({
    get id() { return id; },
    get index() { return index; },
    accept: ['column', 'item'],
    collisionPriority: CollisionPriority.Low,
    type: 'column',
  });
</script>

<div
  {@attach sortable.attach}
  class="container"
  data-shadow={sortable.isDragging ? 'true' : undefined}
>
  <h2>
    {id}
    <button {@attach sortable.attachHandle} class="handle" aria-label="Drag handle"></button>
  </h2>
  <ul>
    {#each rows as itemId, itemIndex (itemId)}
      <SortableItem
        id={itemId}
        column={id}
        index={itemIndex}
        accentColor={colors[id]}
      />
    {/each}
  </ul>
</div>
