// apps/docs/stories/react/components/Container/Container.tsx
import React, {forwardRef} from 'react';

import {classNames} from '../../../utilities';

import styles from './Container.module.css';

export interface Props {
  children: React.ReactNode;
  actions?: React.ReactNode;
  columns?: number;
  label?: string;
  scrollable?: boolean;
  shadow?: boolean;
  style?: React.CSSProperties;
  transitionId?: string;
}

export const Container = forwardRef<HTMLDivElement, Props>(
  (
    {
      actions,
      children,
      columns = 1,
      label,
      style,
      scrollable,
      shadow,
      transitionId,
      ...props
    }: Props,
    ref
  ) => {
    return (
      <div
        {...props}
        ref={ref}
        style={
          {
            ...style,
            viewTransitionName: transitionId,
            '--columns': columns,
          } as React.CSSProperties
        }
        className={classNames(
          styles.Container,
          scrollable && styles.scrollable,
          shadow && styles.shadow
        )}
      >
        {label ? (
          <div className={styles.Header}>
            {label}
            {actions}
          </div>
        ) : null}
        <ul>{children}</ul>
      </div>
    );
  }
);

// apps/stories-solid/components/Item/Container.tsx
import styles from './Container.module.css';
import { JSX, splitProps, mergeProps, createEffect } from 'solid-js';

interface ContainerProps extends JSX.HTMLAttributes<HTMLDivElement> {
  actions?: JSX.Element;
  columns?: number;
  label?: string;
  scrollable?: boolean;
  shadow?: boolean;
  style?: JSX.CSSProperties;
  transitionId?: string;
  children?: JSX.Element;
  ref?: (el: HTMLDivElement) => void;
}

export function Container(props: ContainerProps) {
  const [local, rest] = splitProps(props, [
    'actions',
    'columns',
    'label',
    'scrollable',
    'shadow',
    'style',
    'transitionId',
    'children',
    'ref',
  ]);

  return (
    <div
      {...rest}
      ref={local.ref}
      style={{
        ...local.style,
        'view-transition-name': local.transitionId,
        '--columns': local.columns ?? 1,
      }}
      classList={{
        [styles.Container]: true,
        [styles.scrollable]: !!local.scrollable,
        [styles.shadow]: !!local.shadow,
      }}
    >
      {local.label ? (
        <div class={styles.Header}>
          {local.label}
          {local.actions}
        </div>
      ) : null}
      <ul id={local.label}>{local.children}</ul>
    </div>
  );
}
