// apps/stories-react/stories/components/Dropzone/Dropzone.tsx
import React, {forwardRef} from 'react';

interface Props {
  children: React.ReactNode;
  highlight?: boolean;
}

export const Dropzone = forwardRef<HTMLDivElement, Props>(function Dropzone(
  {children, highlight},
  ref
) {
  return React.createElement(
    'dropzone-component',
    {
      ref,
      'data-highlight': String(highlight),
    },
    children
  );
});

// apps/stories-solid/components/Dropzone/Dropzone.tsx
import './Dropzone.css';
import { ParentProps, splitProps } from 'solid-js';

interface DropzoneProps extends ParentProps {
  ref?: (el: HTMLDivElement) => void;
  highlight?: boolean;
}

export function Dropzone(props: DropzoneProps) {
  const [local, rest] = splitProps(props, ['ref', 'highlight', 'children']);
  return (
    <div
      ref={local.ref}
      class="Dropzone"
      data-highlight={local.highlight}
      {...rest}
    >
      {local.children}
    </div>
  );
}
