// apps/stories/stories/react/components/Actions/Action.tsx
import React, {forwardRef, CSSProperties, Ref} from 'react';

import {classNames} from '@dnd-kit/stories-shared/utilities';

import styles from './Actions.module.css';

export interface Props extends React.HTMLAttributes<HTMLButtonElement> {
  variant?: 'light' | 'dark' | 'destructive';
  cursor?: CSSProperties['cursor'];
}

export const Action = forwardRef<HTMLButtonElement, Props>(
  ({className, cursor, style, variant = 'light', ...props}, ref) => {
    return (
      <button
        ref={ref}
        {...props}
        className={classNames(styles.Action, styles[variant], className)}
        style={
          {
            ...style,
            cursor,
          } as CSSProperties
        }
      />
    );
  }
);

// apps/stories-solid/components/Actions/Action.tsx
import styles from './Actions.module.css';
import { JSX, splitProps } from 'solid-js';
import { classNames } from '@/utilities';

export interface ActionProps extends JSX.ButtonHTMLAttributes<HTMLButtonElement> {
  variant?: 'light' | 'dark' | 'destructive';
  cursor?: string;
}

export function Action(props: ActionProps) {
  const [local, rest] = splitProps(props, [
    'class',
    'style',
    'variant',
    'cursor',
    'ref',
    'children',
  ]);

  const style = () => ({
    ...((typeof local.style === 'object' && local.style !== null) ? local.style : {}),
    cursor: local.cursor,
  });

  return (
    <button
      ref={local.ref}
      {...rest}
      class={classNames(styles.Action, styles[local.variant || 'light'], local.class)}
      style={style()}
    >
      {local.children}
    </button>
  );
}
