// apps/templates/react-sortable/src/App.jsx
import { useState } from 'react';
import { DragDropProvider } from '@dnd-kit/react';
import { useSortable } from '@dnd-kit/react/sortable';
import { move } from '@dnd-kit/helpers';

function SortableItem({ id, index }) {
  const { ref } = useSortable({ id, index });

  return (
    <li ref={ref} className="item">
      Item {id}
    </li>
  );
}

export default function App() {
  const [items, setItems] = useState([1, 2, 3, 4]);

  return (
    <DragDropProvider
      onDragEnd={(event) => {
        setItems((items) => move(items, event));
      }}
    >
      <ul className="list">
        {items.map((id, index) => (
          <SortableItem key={id} id={id} index={index} />
        ))}
      </ul>
    </DragDropProvider>
  );
}

// apps/templates/svelte-sortable/src/App.svelte
<script>
  import {DragDropProvider} from '@dnd-kit/svelte';
  import {createSortable} from '@dnd-kit/svelte/sortable';
  import {move} from '@dnd-kit/helpers';

  let items = $state([1, 2, 3, 4]);

  function onDragEnd(event) {
    items = move(items, event);
  }
</script>

<DragDropProvider {onDragEnd}>
  <ul class="list">
    {#each items as id, index (id)}
      {@const sortable = createSortable({id, index: () => index})}
      <li {@attach sortable.attach} class="item">
        Item {id}
      </li>
    {/each}
  </ul>
</DragDropProvider>
