// apps/stories-vue/stories/Sortable/SortableDynamicFeedbackApp.vue
<script setup lang="ts">
import {ref, computed} from 'vue';
import {Feedback} from '@dnd-kit/dom';
import {DragDropProvider} from '@dnd-kit/vue';
import {useSortable} from '@dnd-kit/vue/sortable';
import {move} from '@dnd-kit/helpers';

const items = ref(Array.from({length: 100}, (_, i) => i + 1));

const dynamicFeedbackPlugin = Feedback.configure({
  feedback: (_source, manager) =>
    manager.dragOperation.activatorEvent instanceof KeyboardEvent
      ? 'clone'
      : 'default',
});

function onDragEnd(event: any) {
  items.value = move(items.value, event);
}
</script>

<script lang="ts">
import {defineComponent} from 'vue';

const SortableItem = defineComponent({
  props: {
    id: {type: Number, required: true},
    index: {type: Number, required: true},
    plugins: {type: Array, default: undefined},
  },
  setup(props) {
    const element = ref<HTMLElement | null>(null);
    const {isDragging} = useSortable({
      id: computed(() => props.id),
      index: computed(() => props.index),
      element,
      plugins: computed(() => props.plugins),
    });
    return {element, isDragging};
  },
  template: `
    <li ref="element" class="item" :data-shadow="isDragging || undefined">
      {{ id }}
    </li>
  `,
});

export default defineComponent({components: {SortableItem}});
</script>

<template>
  <DragDropProvider @dragEnd="onDragEnd">
    <ul class="list">
      <SortableItem
        v-for="(id, index) in items"
        :key="id"
        :id="id"
        :index="index"
        :plugins="[dynamicFeedbackPlugin]"
      />
    </ul>
  </DragDropProvider>
</template>

// apps/stories-solid/stories/Sortable/SortableDynamicFeedbackApp.tsx
import {createSignal, For} from 'solid-js';
import {Feedback} from '@dnd-kit/dom';
import {DragDropProvider} from '@dnd-kit/solid';
import {useSortable} from '@dnd-kit/solid/sortable';
import {move} from '@dnd-kit/helpers';

const dynamicFeedbackPlugin = Feedback.configure({
  feedback: (_source, manager) =>
    manager.dragOperation.activatorEvent instanceof KeyboardEvent
      ? 'clone'
      : 'default',
});

function Sortable(props: {id: number; index: number}) {
  const {isDragging, ref} = useSortable({
    get id() {
      return props.id;
    },
    get index() {
      return props.index;
    },
    plugins: [dynamicFeedbackPlugin],
  });

  return (
    <li ref={ref} class="item" data-shadow={isDragging() ? '' : undefined}>
      {props.id}
    </li>
  );
}

export default function App() {
  const [items, setItems] = createSignal(createRange(100));

  return (
    <DragDropProvider
      onDragEnd={(event) => {
        setItems((items) => move(items, event));
      }}
    >
      <ul class="list">
        <For each={items()}>
          {(id, index) => <Sortable id={id} index={index()} />}
        </For>
      </ul>
    </DragDropProvider>
  );
}

function createRange(length: number) {
  return Array.from({length}, (_, i) => i + 1);
}
