// apps/stories-svelte/stories/Sortable/SortableApp.svelte
<script lang="ts">
  import {DragDropProvider} from '@dnd-kit/svelte';
  import {move} from '@dnd-kit/helpers';
  import SortableItem from './SortableItem.svelte';

  let items = $state(Array.from({length: 100}, (_, i) => i + 1));

  function onDragEnd(event: any) {
    items = move(items, event);
  }
</script>

<DragDropProvider {onDragEnd}>
  <ul class="list">
    {#each items as id, index (id)}
      <SortableItem {id} {index} />
    {/each}
  </ul>
</DragDropProvider>

// apps/stories-solid/stories/Sortable/SortableApp.tsx
import {createSignal, For} from 'solid-js';
import {DragDropProvider} from '@dnd-kit/solid';
import {useSortable} from '@dnd-kit/solid/sortable';
import {move} from '@dnd-kit/helpers';

function Sortable(props: {id: number; index: number}) {
  const {isDragging, ref} = useSortable({
    get id() {
      return props.id;
    },
    get index() {
      return props.index;
    },
  });

  return (
    <li ref={ref} class="item" data-shadow={isDragging() ? '' : undefined}>
      {props.id}
    </li>
  );
}

export default function App() {
  const [items, setItems] = createSignal(createRange(100));

  return (
    <DragDropProvider
      onDragEnd={(event) => {
        setItems((items) => move(items, event));
      }}
    >
      <ul class="list">
        <For each={items()}>
          {(id, index) => <Sortable id={id} index={index()} />}
        </For>
      </ul>
    </DragDropProvider>
  );
}

function createRange(length: number) {
  return Array.from({length}, (_, i) => i + 1);
}
