// apps/stories-solid/stories/Droppable/DroppableApp.tsx
import {createSignal} from 'solid-js';
import {DragDropProvider, useDraggable, useDroppable} from '@dnd-kit/solid';

function Draggable() {
  const {ref} = useDraggable({id: 'draggable'});

  return <button ref={ref} class="btn">draggable</button>;
}

function Droppable(props: {children?: any}) {
  const {isDropTarget, ref} = useDroppable({id: 'droppable'});

  return (
    <div ref={ref} class={isDropTarget() ? 'droppable active' : 'droppable'}>
      {props.children}
    </div>
  );
}

export default function App() {
  const [parent, setParent] = createSignal<string | undefined>();

  return (
    <DragDropProvider
      onDragEnd={(event) => {
        if (event.canceled) return;
        setParent(event.operation.target?.id as string);
      }}
    >
      <section style="display:grid;grid-template-columns:2fr 1fr;gap:20px;align-items:center;max-width:700px;margin:0 auto">
        <div style="display:flex;justify-content:center">
          {parent() == null ? <Draggable /> : null}
        </div>
        <Droppable>
          {parent() === 'droppable' ? <Draggable /> : null}
        </Droppable>
      </section>
    </DragDropProvider>
  );
}

// apps/stories-vue/stories/Droppable/DroppableApp.vue
<script setup lang="ts">
import {ref} from 'vue';
import {DragDropProvider, useDraggable, useDroppable} from '@dnd-kit/vue';

const parent = ref<string | undefined>(undefined);

function onDragEnd(event: any) {
  if (event.canceled) return;
  parent.value = event.operation.target?.id;
}
</script>

<script lang="ts">
import {defineComponent} from 'vue';

const DraggableItem = defineComponent({
  setup() {
    const element = ref<HTMLElement | null>(null);
    useDraggable({id: 'draggable', element});
    return {element};
  },
  template: `<button ref="element" class="btn">draggable</button>`,
});

const DroppableZone = defineComponent({
  setup() {
    const element = ref<HTMLElement | null>(null);
    const {isDropTarget} = useDroppable({id: 'droppable', element});
    return {element, isDropTarget};
  },
  template: `<div ref="element" :class="['droppable', isDropTarget && 'active']"><slot /></div>`,
});

export default defineComponent({components: {DraggableItem, DroppableZone}});
</script>

<template>
  <DragDropProvider @dragEnd="onDragEnd">
    <section style="display:grid;grid-template-columns:2fr 1fr;gap:20px;align-items:center;max-width:700px;margin:0 auto">
      <div style="display:flex;justify-content:center">
        <DraggableItem v-if="parent == null" />
      </div>
      <DroppableZone>
        <DraggableItem v-if="parent === 'droppable'" />
      </DroppableZone>
    </section>
  </DragDropProvider>
</template>
