// packages/solid/src/core/context/renderer.ts
import {batch, createEffect, createSignal, on} from 'solid-js';

import type {DragDropManager} from '@dnd-kit/dom';

type Renderer = DragDropManager['renderer'];

export function useRenderer(): {
  renderer: Renderer;
  trackRendering: (callback: () => void) => void;
} {
  const [transitionCount, setTransitionCount] = createSignal(0);
  let rendering: Promise<void> | null = null;
  let resolver: (() => void) | null = null;

  createEffect(
    on(transitionCount, () => {
      resolver?.();
      rendering = null;
    })
  );

  return {
    renderer: {
      get rendering() {
        return rendering ?? Promise.resolve();
      },
    },
    trackRendering(callback: () => void) {
      if (!rendering) {
        rendering = new Promise<void>((resolve) => {
          resolver = resolve;
        });
      }

      batch(() => {
        callback();
        setTransitionCount((c) => c + 1);
      });
    },
  };
}

// packages/react/src/core/context/renderer.ts
import {useTransition, useState, useRef} from 'react';
import type {Renderer} from '@dnd-kit/abstract';
import {useConstant, useOnValueChange} from '@dnd-kit/react/hooks';

export function useRenderer() {
  const [_, startTransition] = useTransition();
  const [transitionCount, setTransitionCount] = useState(0);
  const rendering = useRef<Promise<void>>();
  const resolver = useRef<() => void>();
  const renderer = useConstant<Renderer>(() => ({
    get rendering() {
      return rendering.current ?? Promise.resolve();
    },
  }));

  useOnValueChange(transitionCount, () => {
    resolver.current?.();
    rendering.current = undefined;
  });

  return {
    renderer,
    trackRendering(callback: () => void) {
      if (!rendering.current) {
        rendering.current = new Promise<void>((resolve) => {
          resolver.current = resolve;
        });
      }

      startTransition(() => {
        callback();
        setTransitionCount((count) => count + 1);
      });
    },
  };
}
