// packages/solid/src/core/context/DragDropProvider.tsx
import { DragDropManager, defaultPreset } from '@dnd-kit/dom';
import { createEffect, createMemo, onCleanup } from 'solid-js';

import { DragDropContext } from './context.ts';
import { useRenderer } from '../hooks/useRenderer.ts';

import type { DragDropEvents } from '@dnd-kit/abstract';
import type { DragDropManagerInput, Draggable, Droppable } from '@dnd-kit/dom';
import type { ParentProps } from 'solid-js';

export type Events = DragDropEvents<Draggable, Droppable, DragDropManager>;

export interface DragDropProviderProps extends DragDropManagerInput, ParentProps {
    manager?: DragDropManager;
    onBeforeDragStart?: Events['beforedragstart'];
    onCollision?: Events['collision'];
    onDragStart?: Events['dragstart'];
    onDragMove?: Events['dragmove'];
    onDragOver?: Events['dragover'];
    onDragEnd?: Events['dragend'];
}

export function DragDropProvider(props: DragDropProviderProps) {
    const { renderer, trackRendering } = useRenderer();
    const manager = createMemo(() => props.manager ?? new DragDropManager());

    // Destroy the manager if we created it ourselves
    onCleanup(() => {
        if (!props.manager) {
            manager().destroy();
        }
    });

    // Sync the manager with the input
    createEffect(() => {
        const _manager = manager();
        
        if (!_manager) {
            return;
        }

        _manager.renderer = renderer;
        _manager.plugins = props.plugins ?? defaultPreset.plugins;
        _manager.sensors = props.sensors ?? defaultPreset.sensors;
        _manager.modifiers = props.modifiers ?? defaultPreset.modifiers;
    });
    
    // Set up event listeners
    createEffect(() => {
        const disposers: (() => void)[] = [];
        const monitor = manager().monitor;
        
        disposers.push(
            monitor.addEventListener('beforedragstart', (event, manager) => {
                const callback = props.onBeforeDragStart;

                if (callback) {
                    trackRendering(() => callback(event, manager));
                }
            }),

            monitor.addEventListener('dragstart', (event, manager) => {
                props.onDragStart?.(event, manager);
            }),

            monitor.addEventListener('dragover', (event, manager) => {
                const callback = props.onDragOver;

                if (callback) {
                    trackRendering(() => callback(event, manager));
                }
            }),

            monitor.addEventListener('dragmove', (event, manager) => {
                const callback = props.onDragMove;

                if (callback) {
                    trackRendering(() => callback(event, manager));
                }
            }),

            monitor.addEventListener('dragend', (event, manager) => {
                const callback = props.onDragEnd;
                console.log('dragend', event, manager, callback);

                if (callback) {
                    trackRendering(() => callback(event, manager));
                }
            }),

            monitor.addEventListener('collision', (event, manager) => {
                const callback = props.onCollision;

                if (callback) {
                    callback(event, manager);
                }
            }),
        );

        // Clean up all event listeners
        onCleanup(() => {
            disposers.forEach(cleanup => cleanup());
        });
    });

    return (
        <DragDropContext.Provider value={ manager() }>
            {props.children}
        </DragDropContext.Provider>
    );
}

// packages/react/src/context/DragDropProvider.tsx
import {
  forwardRef,
  useImperativeHandle,
  useEffect,
  type PropsWithChildren,
} from 'react';
import {type DragDropEvents} from '@dnd-kit/abstract';
import {DragDropManager, defaultPreset} from '@dnd-kit/dom';
import type {DragDropManagerInput, Draggable, Droppable} from '@dnd-kit/dom';

import {useConstant, useEvent, useLatest, useOnValueChange} from '../hooks';

import {DragDropContext} from './context';
import {useRenderer} from './renderer';

type Events = DragDropEvents<Draggable, Droppable, DragDropManager>;

export interface Props extends DragDropManagerInput, PropsWithChildren {
  onBeforeDragStart?: Events['beforedragstart'];
  onCollision?: Events['collision'];
  onDragStart?: Events['dragstart'];
  onDragOver?: Events['dragover'];
  onDragEnd?: Events['dragend'];
}

export const DragDropProvider = forwardRef<DragDropManager, Props>(
  function DragDropProvider(
    {
      children,
      onCollision,
      onBeforeDragStart,
      onDragStart,
      onDragOver,
      onDragEnd,
      ...input
    },
    ref
  ) {
    const {renderer, trackRendering} = useRenderer();
    const manager = useConstant(
      () => new DragDropManager({...input, renderer})
    );
    const {plugins} = input;
    const handleBeforeDragStart = useLatest(onBeforeDragStart);
    const handleDragStart = useEvent(onDragStart);
    const handleDragOver = useLatest(onDragOver);
    const handleDragEnd = useLatest(onDragEnd);
    const handleCollision = useEvent(onCollision);

    useEffect(() => {
      manager.monitor.addEventListener('beforedragstart', (event, manager) => {
        const callback = handleBeforeDragStart.current;

        if (callback) {
          trackRendering(() => callback(event, manager));
        }
      });
      manager.monitor.addEventListener('dragstart', handleDragStart);
      manager.monitor.addEventListener('dragover', (event, manager) => {
        const callback = handleDragOver.current;

        if (callback) {
          trackRendering(() => callback(event, manager));
        }
      });
      manager.monitor.addEventListener('dragend', (event, manager) => {
        const callback = handleDragEnd.current;

        if (callback) {
          trackRendering(() => callback(event, manager));
        }
      });
      manager.monitor.addEventListener('collision', handleCollision);

      return () => {
        manager.destroy();
      };
    }, []);

    useOnValueChange(
      plugins,
      () => (manager.plugins = plugins ?? defaultPreset.plugins)
    );

    useImperativeHandle(ref, () => manager, [manager]);

    return (
      <DragDropContext.Provider value={manager}>
        {children}
      </DragDropContext.Provider>
    );
  }
);
