// packages/react/src/core/droppable/useDroppable.ts
import {useCallback} from 'react';
import type {Data} from '@dnd-kit/abstract';
import {Droppable} from '@dnd-kit/dom';
import {deepEqual} from '@dnd-kit/state';
import type {DroppableInput} from '@dnd-kit/dom';
import {useComputed, useOnValueChange} from '@dnd-kit/react/hooks';
import {currentValue, type RefOrValue} from '@dnd-kit/react/utilities';

import {useInstance} from '../hooks/useInstance.ts';

export interface UseDroppableInput<T extends Data = Data>
  extends Omit<DroppableInput<T>, 'element'> {
  element?: RefOrValue<Element>;
}

export function useDroppable<T extends Data = Data>(
  input: UseDroppableInput<T>
) {
  const {collisionDetector, disabled, id, accept, type} = input;
  const element = currentValue(input.element);
  const droppable = useInstance(
    (manager) =>
      new Droppable(
        {
          ...input,
          element,
          options: {
            ...input.options,
            register: false,
          },
        },
        manager
      )
  );
  const isDropTarget = useComputed(() => droppable.isDropTarget);

  useOnValueChange(id, () => (droppable.id = id));
  useOnValueChange(accept, () => (droppable.id = id), undefined, deepEqual);
  useOnValueChange(collisionDetector, () => (droppable.id = id));
  useOnValueChange(disabled, () => (droppable.disabled = disabled === true));
  useOnValueChange(element, () => (droppable.element = element));
  useOnValueChange(type, () => (droppable.id = id));

  return {
    get isDropTarget() {
      return isDropTarget.value;
    },
    ref: useCallback(
      (element: Element | null) => {
        droppable.element = element ?? undefined;
      },
      [droppable]
    ),
    droppable,
  };
}

// packages/solid/src/core/droppable/useDroppable.ts
import type {Data} from '@dnd-kit/abstract';
import type {DroppableInput} from '@dnd-kit/dom';
import {Droppable} from '@dnd-kit/dom';
import {createEffect, createSignal} from 'solid-js';

import {useDeepSignal} from '../../hooks/useDeepSignal.ts';
import {useInstance} from '../hooks/useInstance.ts';

export interface UseDroppableInput<T extends Data = Data>
  extends Omit<DroppableInput<T>, 'element'> {
  element?: Element;
}

export function useDroppable<T extends Data = Data>(
  input: UseDroppableInput<T>
) {
  const droppable = useInstance(
    (manager) =>
      new Droppable(
        {
          ...input,
          register: false,
          element: input.element,
        },
        manager
      )
  );
  const trackedDroppable = useDeepSignal(() => droppable);

  const [element, setElement] = createSignal<Element | undefined>(
    input.element
  );

  createEffect(() => {
    const el = element();
    if (el) droppable.element = el;

    droppable.id = input.id;
    droppable.accept = input.accept;
    droppable.type = input.type;
    droppable.disabled = input.disabled ?? false;

    if (input.collisionDetector) {
      droppable.collisionDetector = input.collisionDetector;
    }

    if (input.data) {
      droppable.data = input.data;
    }
  });

  return {
    get droppable() {
      return droppable;
    },
    get isDropTarget() {
      return trackedDroppable().isDropTarget;
    },
    ref: setElement,
  };
}
