// packages/react/src/droppable/useDroppable.ts
import {useCallback, useEffect} from 'react';
import type {Data} from '@dnd-kit/abstract';
import {Droppable} from '@dnd-kit/dom';
import type {DroppableInput} from '@dnd-kit/dom';

import {useDragDropManager} from '../context';
import {useComputed, useConstant, useOnValueChange} from '../hooks';
import {getCurrentValue, type RefOrValue} from '../utilities';
import {deepEqual} from '@dnd-kit/state';

export interface UseDroppableInput<T extends Data = Data>
  extends Omit<DroppableInput<T>, 'element'> {
  element?: RefOrValue<Element>;
}

export function useDroppable<T extends Data = Data>(
  input: UseDroppableInput<T>
) {
  const manager = useDragDropManager();
  const {collisionDetector, disabled, id, accept, type} = input;
  const element = getCurrentValue(input.element);
  const droppable = useConstant(
    () => new Droppable({...input, element}, manager)
  );
  const isDisabled = useComputed(() => droppable.disabled);
  const isDropTarget = useComputed(() => droppable.isDropTarget);

  useOnValueChange(id, () => (droppable.id = id));
  useOnValueChange(accept, () => (droppable.id = id), undefined, deepEqual);
  useOnValueChange(collisionDetector, () => (droppable.id = id));
  useOnValueChange(disabled, () => (droppable.disabled = disabled === true));
  useOnValueChange(element, () => (droppable.element = element));
  useOnValueChange(type, () => (droppable.id = id));

  useEffect(() => {
    // Cleanup on unmount
    return droppable.destroy;
  }, [droppable]);

  return {
    get isDisabled() {
      return isDisabled.value;
    },
    get isDropTarget() {
      return isDropTarget.value;
    },
    ref: useCallback(
      (element: Element | null) => {
        droppable.element = element ?? undefined;
      },
      [droppable]
    ),
  };
}

// packages/solid/src/core/droppable/useDroppable.ts
import type {Data} from '@dnd-kit/abstract';
import type {DroppableInput} from '@dnd-kit/dom';
import {Droppable} from '@dnd-kit/dom';
import {createEffect, createSignal} from 'solid-js';

import {useDeepSignal} from '../../hooks/useDeepSignal.ts';
import {useInstance} from '../hooks/useInstance.ts';

export interface UseDroppableInput<T extends Data = Data>
  extends Omit<DroppableInput<T>, 'element'> {
  element?: Element;
}

export function useDroppable<T extends Data = Data>(
  input: UseDroppableInput<T>
) {
  const droppable = useInstance(
    (manager) =>
      new Droppable(
        {
          ...input,
          register: false,
          element: input.element,
        },
        manager
      )
  );
  const trackedDroppable = useDeepSignal(() => droppable);

  const [element, setElement] = createSignal<Element | undefined>(
    input.element
  );

  createEffect(() => {
    const el = element();
    if (el) droppable.element = el;

    droppable.id = input.id;
    droppable.accept = input.accept;
    droppable.type = input.type;
    droppable.disabled = input.disabled ?? false;

    if (input.collisionDetector) {
      droppable.collisionDetector = input.collisionDetector;
    }

    if (input.data) {
      droppable.data = input.data;
    }
  });

  return {
    get droppable() {
      return droppable;
    },
    get isDropTarget() {
      return trackedDroppable().isDropTarget;
    },
    ref: setElement,
  };
}
