// apps/stories-solid/stories/Sortable/MultipleLists/MultipleListsApp.tsx
import {createSignal, For} from 'solid-js';
import {CollisionPriority} from '@dnd-kit/abstract';
import {DragDropProvider} from '@dnd-kit/solid';
import {useSortable} from '@dnd-kit/solid/sortable';
import {defaultPreset, PointerSensor, KeyboardSensor} from '@dnd-kit/dom';
import {move} from '@dnd-kit/helpers';

function createRange(length: number) {
  return Array.from({length}, (_, i) => i + 1);
}

function cloneDeep<T>(obj: T): T {
  return JSON.parse(JSON.stringify(obj));
}

const ITEM_COUNT = 6;

const COLORS: Record<string, string> = {
  A: '#7193f1',
  B: '#FF851B',
  C: '#2ECC40',
  D: '#ff3680',
};

const sensors = [
  PointerSensor.configure({
    activatorElements(source) {
      return [source.element, source.handle];
    },
  }),
  KeyboardSensor,
];

function SortableItem(props: {id: string; column: string; index: number}) {
  const {isDragging, ref, handleRef} = useSortable({
    get id() { return props.id; },
    get index() { return props.index; },
    get group() { return props.column; },
    get data() { return {group: props.column}; },
    accept: 'item',
    type: 'item',
    feedback: 'clone',
  });

  return (
    <li
      ref={ref}
      class="item"
      data-shadow={isDragging() ? 'true' : undefined}
      data-accent-color={props.column}
      style={{'--accent-color': COLORS[props.column]}}
    >
      {props.id}
      <button ref={handleRef} class="handle" />
    </li>
  );
}

function SortableColumn(props: {id: string; index: number; rows: string[]}) {
  const {isDragging, ref, handleRef} = useSortable({
    get id() { return props.id; },
    get index() { return props.index; },
    accept: ['column', 'item'],
    collisionPriority: CollisionPriority.Low,
    type: 'column',
  });

  return (
    <div
      ref={ref}
      class="container"
      data-shadow={isDragging() ? 'true' : undefined}
    >
      <div class="container-header">
        {props.id}
        <button ref={handleRef} class="handle" />
      </div>
      <ul>
        <For each={props.rows}>
          {(itemId, itemIndex) => (
            <SortableItem id={itemId} column={props.id} index={itemIndex()} />
          )}
        </For>
      </ul>
    </div>
  );
}

export default function App() {
  const [items, setItems] = createSignal<Record<string, string[]>>({
    A: createRange(ITEM_COUNT).map((id) => `A${id}`),
    B: createRange(ITEM_COUNT).map((id) => `B${id}`),
    C: createRange(ITEM_COUNT).map((id) => `C${id}`),
    D: [],
  });

  const columns = Object.keys(items());
  let snapshot = cloneDeep(items());

  return (
    <DragDropProvider
      plugins={defaultPreset.plugins}
      sensors={sensors}
      onDragStart={() => {
        snapshot = cloneDeep(items());
      }}
      onDragOver={(event) => {
        const {source} = event.operation;
        if (source?.type === 'column') return;
        setItems((items) => move(items, event));
      }}
      onDragEnd={(event) => {
        if (event.canceled) {
          setItems(snapshot);
        }
      }}
    >
      <div class="multiple-lists-container">
        <For each={columns}>
          {(column, columnIndex) => (
            <SortableColumn
              id={column}
              index={columnIndex()}
              rows={items()[column]}
            />
          )}
        </For>
      </div>
    </DragDropProvider>
  );
}

// apps/stories/stories/react/Sortable/MultipleLists/MultipleListsApp.tsx
import React, {memo, useCallback, useRef, useState} from 'react';
import type {PropsWithChildren} from 'react';
import {CollisionPriority} from '@dnd-kit/abstract';
import {DragDropProvider} from '@dnd-kit/react';
import {useSortable} from '@dnd-kit/react/sortable';
import {move} from '@dnd-kit/helpers';
import {defaultPreset, PointerSensor, KeyboardSensor} from '@dnd-kit/dom';
import {DragDropEventHandlers} from '@dnd-kit/react';

function createRange(length: number) {
  return Array.from({length}, (_, i) => i + 1);
}

function cloneDeep<T>(obj: T): T {
  return JSON.parse(JSON.stringify(obj));
}

const ITEM_COUNT = 6;

const sensors = [
  PointerSensor.configure({
    activatorElements(source) {
      return [source.element, source.handle];
    },
  }),
  KeyboardSensor,
];

interface SortableItemProps {
  id: string;
  column: string;
  index: number;
  accentColor: string;
}

const COLORS: Record<string, string> = {
  A: '#7193f1',
  B: '#FF851B',
  C: '#2ECC40',
  D: '#ff3680',
};

const SortableItem = memo(function SortableItem({
  id,
  column,
  index,
  accentColor,
}: PropsWithChildren<SortableItemProps>) {
  const group = column;
  const {handleRef, ref, isDragging} = useSortable({
    id,
    group,
    accept: 'item',
    type: 'item',
    feedback: 'clone',
    index,
    data: {group},
  });

  return (
    <div
      ref={ref as any}
      className="item"
      data-shadow={isDragging || undefined}
      data-accent-color={accentColor}
      style={{'--accent-color': accentColor} as React.CSSProperties}
    >
      {id}
      <button ref={handleRef as any} className="handle" />
    </div>
  );
});

interface SortableColumnProps {
  id: string;
  index: number;
  rows: string[];
}

const SortableColumn = memo(function SortableColumn({
  rows,
  id,
  index,
}: PropsWithChildren<SortableColumnProps>) {
  const {handleRef, isDragging, ref} = useSortable({
    id,
    accept: ['column', 'item'],
    collisionPriority: CollisionPriority.Low,
    type: 'column',
    index,
  });

  return (
    <div
      ref={ref as any}
      className="container"
      data-shadow={isDragging || undefined}
    >
      <div className="container-header">
        {id}
        <button ref={handleRef as any} className="handle" />
      </div>
      <ul style={{'--columns': 1} as React.CSSProperties}>
        {rows.map((itemId, itemIndex) => (
          <SortableItem
            key={itemId}
            id={itemId}
            column={id}
            index={itemIndex}
            accentColor={COLORS[id]}
          />
        ))}
      </ul>
    </div>
  );
});

export default function App() {
  const [items, setItems] = useState({
    A: createRange(ITEM_COUNT).map((id) => `A${id}`),
    B: createRange(ITEM_COUNT).map((id) => `B${id}`),
    C: createRange(ITEM_COUNT).map((id) => `C${id}`),
    D: [],
  });
  const [columns] = useState(Object.keys(items));
  const snapshot = useRef(cloneDeep(items));

  return (
    <DragDropProvider
      plugins={defaultPreset.plugins}
      sensors={sensors}
      onDragStart={useCallback<DragDropEventHandlers['onDragStart']>(() => {
        snapshot.current = cloneDeep(items);
      }, [items])}
      onDragOver={useCallback<DragDropEventHandlers['onDragOver']>((event) => {
        const {source} = event.operation;

        if (source?.type === 'column') {
          return;
        }

        setItems((items) => move(items, event));
      }, [])}
      onDragEnd={useCallback<DragDropEventHandlers['onDragEnd']>((event) => {
        if (event.canceled) {
          setItems(snapshot.current);
          return;
        }
      }, [])}
    >
      <div className="multiple-lists-container">
        {columns.map((column, columnIndex) => {
          const rows = items[column];

          return (
            <SortableColumn
              key={column}
              id={column}
              index={columnIndex}
              rows={rows}
            />
          );
        })}
      </div>
    </DragDropProvider>
  );
}
