// apps/templates/react-draggable/src/App.jsx
import {useState} from 'react';
import {DragDropProvider, useDraggable} from '@dnd-kit/react';
import {Droppable} from './Droppable';
import './styles.css';

function Draggable() {
  const {ref} = useDraggable({id: 'draggable'});
  return <button ref={ref} className="btn">draggable</button>;
}

export default function App() {
  const [parent, setParent] = useState(undefined);
  return (
    <DragDropProvider
      onDragEnd={(event) => {
        if (event.canceled) return;
        setParent(event.operation.target?.id);
      }}
    >
      <div className="container">
        {parent == null ? <Draggable /> : null}
        <Droppable>
          {parent === 'droppable' ? <Draggable /> : null}
        </Droppable>
      </div>
    </DragDropProvider>
  );
}

// apps/templates/vue-draggable/src/App.vue
<script setup>
import { ref } from 'vue';
import { DragDropProvider } from '@dnd-kit/vue';
import Draggable from './Draggable.vue';
import Droppable from './Droppable.vue';
import './styles.css';

const parent = ref(undefined);

function onDragEnd(event) {
  if (event.canceled) return;
  parent.value = event.operation.target?.id;
}
</script>

<template>
  <DragDropProvider @dragEnd="onDragEnd">
    <div class="container">
      <Draggable v-if="parent == null" />
      <Droppable>
        <Draggable v-if="parent === 'droppable'" />
      </Droppable>
    </div>
  </DragDropProvider>
</template>
