// apps/docs/.storybook/preview.tsx
import React from 'react';
import {Unstyled} from '@storybook/blocks';

import {Button, Dropzone, Code} from '../stories/components';

// Register web components
customElements.define('button-component', Button);
customElements.define('dropzone-component', Dropzone);

const preview = {
  parameters: {
    docs: {
      components: {
        pre: (props) => (
          <Unstyled>
            <pre {...props} />
          </Unstyled>
        ),
        code: Code,
      },
    },
    darkMode: {
      stylePreview: true,
    },
    options: {
      storySort: {
        order: [
          'Docs',
          'React',
          [
            'Draggable',
            'Droppable',
            'Sortable',
            ['Vertical', 'Horizontal', 'Grid'],
          ],
        ],
      },
    },
  },
};

export default preview;

// apps/docs/.storybook/preview.jsx
import React from 'react';
import {Unstyled} from '@storybook/blocks';

import {Code} from '../stories/react/components';

export const parameters = {
  docs: {
    components: {
      pre: (props) => (
        <Unstyled>
          <pre {...props} />
        </Unstyled>
      ),
      code: Code,
    },
  },
};

const preview = {
  parameters: {
    options: {
      storySort: {
        order: ['Docs', ['Docs']],
      },
    },
  },
};

export default preview;
