// apps/stories-solid/stories/Draggable/DraggableExample.tsx
import {createSignal, JSX, Show} from 'solid-js';
import type {Modifiers, Sensors} from '@dnd-kit/abstract';
import {DragDropProvider, DragOverlay, useDraggable} from '@dnd-kit/solid';

import {Button} from '@/components/Button/Button';
import {DraggableIcon} from '@/components/icons/DraggableIcon';
import { Handle } from '@/components/Actions/Handle';

interface Props {
  container?: (props: {children: JSX.Element}) => JSX.Element | string;
  handle?: boolean;
  overlay?: boolean;
  modifiers?: Modifiers;
  sensors?: Sensors;
}

export function DraggableExample(props: Props) {
  return (
    <DragDropProvider sensors={props.sensors}>
        <Draggable id="draggable" {...props} />
        <Show when={props.overlay}>
          <DragOverlay>
            <Button shadow style={{width: '100%'}}>
              Drag overlay
              <Handle variant="dark" />
            </Button>
          </DragOverlay>
        </Show>
    </DragDropProvider>
  );
}

interface DraggableProps {
  id: string;
  handle?: boolean;
  feedback?: any;
  modifiers?: Modifiers;
  style?: any;
  overlay?: boolean;
}

export function Draggable({
  id,
  modifiers,
  handle,
  feedback,
  style,
  overlay,
}: DraggableProps) {
  const {isDragging, ref, handleRef} = useDraggable({
    id,
    modifiers,
    feedback,
  });

  return (
    <Button
      ref={ref}
      disabled={isDragging() && overlay}
      shadow={isDragging() && !overlay}
      style={style}
    >
      {handle ? <Handle ref={handleRef} variant="dark" /> : null}
      <DraggableIcon />
    </Button>
  );
}

// apps/stories/stories/react/Draggable/DraggableExample.tsx
import React, {
  type PropsWithChildren,
  type CSSProperties,
  useRef,
  useState,
} from 'react';
import type {Modifiers, Sensors} from '@dnd-kit/abstract';
import type {FeedbackType} from '@dnd-kit/dom';
import {DragDropProvider, DragOverlay, useDraggable} from '@dnd-kit/react';

import {Button, Handle} from '../components';
import {DraggableIcon} from '../icons';

interface Props {
  container?: React.FC<PropsWithChildren<{}>> | string;
  handle?: boolean;
  overlay?: boolean;
  modifiers?: Modifiers;
  sensors?: Sensors;
}

export function DraggableExample(props: Props) {
  const {container, overlay, sensors} = props;
  const Wrapper = container ?? 'div';

  return (
    <DragDropProvider sensors={sensors}>
      <Wrapper>
        <Draggable id="draggable" {...props} />
        {overlay && (
          <DragOverlay>
            <Button shadow style={{width: '100%'}}>
              Drag overlay
              <Handle variant="dark" />
            </Button>
          </DragOverlay>
        )}
      </Wrapper>
    </DragDropProvider>
  );
}

interface DraggableProps {
  id: string;
  handle?: boolean;
  feedback?: FeedbackType;
  modifiers?: Modifiers;
  style?: CSSProperties;
  overlay?: boolean;
}

export function Draggable({
  id,
  modifiers,
  handle,
  feedback,
  style,
  overlay,
}: DraggableProps) {
  const [element, setElement] = useState<Element | null>(null);
  const handleRef = useRef<HTMLButtonElement | null>(null);

  const {isDragging} = useDraggable({
    id,
    modifiers,
    element,
    feedback,
    handle: handleRef,
  });

  return (
    <Button
      ref={setElement}
      actions={handle ? <Handle ref={handleRef} variant="dark" /> : undefined}
      disabled={isDragging && overlay}
      shadow={isDragging && !overlay}
      style={style}
    >
      <DraggableIcon />
    </Button>
  );
}
