// packages/solid/src/sortable/useSortable.ts
import {type Data} from '@dnd-kit/abstract';
import type {SortableInput} from '@dnd-kit/dom/sortable';
import {defaultSortableTransition, Sortable} from '@dnd-kit/dom/sortable';
import {batch} from '@dnd-kit/state';
import {createEffect, createSignal, on} from 'solid-js';

import {useDeepSignal} from '../hooks/useDeepSignal.ts';
import {useInstance} from '../core/hooks/useInstance.ts';

export interface UseSortableInput<T extends Data = Data>
  extends Omit<SortableInput<T>, 'handle' | 'element' | 'source' | 'target'> {
  handle?: Element;
  element?: Element;
  source?: Element;
  target?: Element;
}

export function useSortable<T extends Data = Data>(
  input: UseSortableInput<T>
) {
  const transition = {
    ...defaultSortableTransition,
    ...input.transition,
  };

  const sortable = useInstance((manager) => {
    return new Sortable(
      {
        ...input,
        register: false,
        transition,
        element: input.element,
        handle: input.handle,
        target: input.target,
      },
      manager
    );
  });
  const trackedSortable = useDeepSignal(() => sortable);

  const [element, setElement] = createSignal<Element | undefined>(
    input.element
  );
  const [handle, setHandle] = createSignal<Element | undefined>(input.handle);
  const [source, setSource] = createSignal<Element | undefined>(input.source);
  const [target, setTarget] = createSignal<Element | undefined>(input.target);

  createEffect(() => {
    const el = element();
    if (el) sortable.element = el;

    const h = handle();
    if (h) sortable.handle = h;

    const s = source();
    if (s) sortable.source = s;

    const t = target();
    if (t) sortable.target = t;

    sortable.id = input.id;
    sortable.disabled = input.disabled ?? false;
    sortable.feedback = input.feedback ?? 'default';
    sortable.alignment = input.alignment;
    sortable.modifiers = input.modifiers;
    sortable.sensors = input.sensors;
    sortable.accept = input.accept;
    sortable.type = input.type;
    sortable.collisionPriority = input.collisionPriority;
    sortable.transition = input.transition
      ? {...defaultSortableTransition, ...input.transition}
      : defaultSortableTransition;

    if (input.collisionDetector) {
      sortable.collisionDetector = input.collisionDetector;
    }

    if (input.data) {
      sortable.data = input.data;
    }
  });

  // Batch group + index updates
  createEffect(
    on(
      () => [input.group, input.index],
      () => {
        batch(() => {
          sortable.group = input.group;
          sortable.index = input.index;
        });
      }
    )
  );

  // Refresh shape when index changes while idle
  createEffect(
    on(
      () => input.index,
      () => {
        if (
          sortable.manager?.dragOperation.status.idle &&
          sortable.transition?.idle
        ) {
          sortable.refreshShape();
        }
      }
    )
  );

  return {
    get sortable() {
      return sortable;
    },
    get isDragging() {
      return trackedSortable().isDragging;
    },
    get isDropping() {
      return trackedSortable().isDropping;
    },
    get isDragSource() {
      return trackedSortable().isDragSource;
    },
    get isDropTarget() {
      return trackedSortable().isDropTarget;
    },
    ref: setElement,
    handleRef: setHandle,
    sourceRef: setSource,
    targetRef: setTarget,
  };
}

// packages/react/src/sortable/useSortable.ts
import {useCallback} from 'react';
import {batch, deepEqual} from '@dnd-kit/state';
import {type Data} from '@dnd-kit/abstract';
import {Sortable, defaultSortableTransition} from '@dnd-kit/dom/sortable';
import type {SortableInput} from '@dnd-kit/dom/sortable';
import {useInstance} from '@dnd-kit/react';
import {
  useComputed,
  useImmediateEffect as immediateEffect,
  useIsomorphicLayoutEffect,
  useOnValueChange,
  useOnElementChange,
  useDeepSignal,
} from '@dnd-kit/react/hooks';
import {currentValue, type RefOrValue} from '@dnd-kit/react/utilities';

export interface UseSortableInput<T extends Data = Data>
  extends Omit<SortableInput<T>, 'handle' | 'element' | 'target'> {
  handle?: RefOrValue<Element>;
  element?: RefOrValue<Element>;
  target?: RefOrValue<Element>;
}

export function useSortable<T extends Data = Data>(input: UseSortableInput<T>) {
  const {
    accept,
    collisionDetector,
    collisionPriority,
    id,
    data,
    element,
    handle,
    index,
    group,
    disabled,
    feedback,
    modifiers,
    sensors,
    target,
    transition = defaultSortableTransition,
    type,
  } = input;
  const sortable = useInstance((manager) => {
    return new Sortable(
      {
        ...input,
        register: false,
        handle: currentValue(handle),
        element: currentValue(element),
        target: currentValue(target),
        feedback,
      },
      manager
    );
  });

  const trackedSortable = useDeepSignal(sortable);

  useOnValueChange(id, () => (sortable.id = id));

  useIsomorphicLayoutEffect(() => {
    batch(() => {
      sortable.group = group;
      sortable.index = index;
    });
  }, [sortable, group, index]);

  useOnValueChange(type, () => (sortable.type = type));
  useOnValueChange(
    accept,
    () => (sortable.accept = accept),
    undefined,
    deepEqual
  );
  useOnValueChange(data, () => data && (sortable.data = data));
  useOnValueChange(
    index,
    () => {
      if (sortable.manager?.dragOperation.status.idle && transition?.idle) {
        sortable.refreshShape();
      }
    },
    immediateEffect
  );
  useOnElementChange(handle, (handle) => (sortable.handle = handle));
  useOnElementChange(element, (element) => (sortable.element = element));
  useOnElementChange(target, (target) => (sortable.target = target));
  useOnValueChange(disabled, () => (sortable.disabled = disabled === true));
  useOnValueChange(sensors, () => (sortable.sensors = sensors));
  useOnValueChange(
    collisionDetector,
    () => (sortable.collisionDetector = collisionDetector)
  );
  useOnValueChange(
    collisionPriority,
    () => (sortable.collisionPriority = collisionPriority)
  );
  useOnValueChange(feedback, () => (sortable.feedback = feedback ?? 'default'));
  useOnValueChange(transition, () => (sortable.transition = transition));
  useOnValueChange(
    modifiers,
    () => (sortable.modifiers = modifiers),
    undefined,
    deepEqual
  );

  return {
    sortable: trackedSortable,
    get isDragging() {
      return trackedSortable.isDragging;
    },
    get isDropping() {
      return trackedSortable.isDropping;
    },
    get isDragSource() {
      return trackedSortable.isDragSource;
    },
    get isDropTarget() {
      return trackedSortable.isDropTarget;
    },
    handleRef: useCallback(
      (element: Element | null) => {
        sortable.handle = element ?? undefined;
      },
      [sortable]
    ),
    ref: useCallback(
      (element: Element | null) => {
        if (
          !element &&
          sortable.element?.isConnected &&
          !sortable.manager?.dragOperation.status.idle
        ) {
          return;
        }

        sortable.element = element ?? undefined;
      },
      [sortable]
    ),
    sourceRef: useCallback(
      (element: Element | null) => {
        if (
          !element &&
          sortable.source?.isConnected &&
          !sortable.manager?.dragOperation.status.idle
        ) {
          return;
        }

        sortable.source = element ?? undefined;
      },
      [sortable]
    ),
    targetRef: useCallback(
      (element: Element | null) => {
        if (
          !element &&
          sortable.target?.isConnected &&
          !sortable.manager?.dragOperation.status.idle
        ) {
          return;
        }

        sortable.target = element ?? undefined;
      },
      [sortable]
    ),
  };
}
