// apps/stories/stories/react/Droppable/MultipleDroppable/MultipleDroppableApp.tsx
import React, {useState} from 'react';
import {DragDropProvider, useDraggable, useDroppable} from '@dnd-kit/react';

function Draggable({id}: {id: string}) {
  const {ref} = useDraggable({id});

  return <button ref={ref} className="btn">draggable</button>;
}

function Droppable({id, children}: {id: string; children?: React.ReactNode}) {
  const {ref, isDropTarget} = useDroppable({id});

  return (
    <div ref={ref} className={isDropTarget ? "droppable active" : "droppable"}>
      {children}
    </div>
  );
}

export default function App() {
  const [parent, setParent] = useState<string | undefined>(undefined);
  const draggable = <Draggable id="draggable" />;
  const droppables = ['A', 'B', 'C'];

  return (
    <DragDropProvider
      onDragEnd={(event) => {
        if (event.canceled) return;
        setParent(event.operation.target?.id as string);
      }}
    >
      <div style={{display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 20, maxWidth: 500, margin: '0 auto'}}>
        <div style={{display: 'flex', alignItems: 'center', justifyContent: 'center'}}>
          {parent == null ? draggable : null}
        </div>
        {droppables.map((id) => (
          <Droppable key={id} id={id}>
            {parent === id ? draggable : null}
          </Droppable>
        ))}
      </div>
    </DragDropProvider>
  );
}

// apps/stories-solid/stories/Droppable/MultipleDroppable/MultipleDroppableApp.tsx
import {createSignal, For} from 'solid-js';
import {DragDropProvider, useDraggable, useDroppable} from '@dnd-kit/solid';

function Draggable() {
  const {ref} = useDraggable({id: 'draggable'});

  return <button ref={ref} class="btn">draggable</button>;
}

function Droppable(props: {id: string; children?: any}) {
  const {isDropTarget, ref} = useDroppable({id: props.id});

  return (
    <div ref={ref} class={isDropTarget() ? 'droppable active' : 'droppable'}>
      {props.children}
    </div>
  );
}

export default function App() {
  const [parent, setParent] = createSignal<string | undefined>();
  const droppables = ['A', 'B', 'C'];

  return (
    <DragDropProvider
      onDragEnd={(event) => {
        if (event.canceled) return;
        setParent(event.operation.target?.id as string);
      }}
    >
      <div style={{display: 'grid', 'grid-template-columns': '1fr 1fr', gap: '20px', 'max-width': '500px', margin: '0 auto'}}>
        <div style={{display: 'flex', 'align-items': 'center', 'justify-content': 'center'}}>
          {parent() == null ? <Draggable /> : null}
        </div>
        <For each={droppables}>
          {(id) => (
            <Droppable id={id}>
              {parent() === id ? <Draggable /> : null}
            </Droppable>
          )}
        </For>
      </div>
    </DragDropProvider>
  );
}
