// apps/templates/svelte-draggable/src/App.svelte
<script>
  import {DragDropProvider, createDraggable, createDroppable} from '@dnd-kit/svelte';

  let parent = $state(undefined);

  function onDragEnd(event) {
    if (event.canceled) return;
    parent = event.operation.target?.id;
  }

  const draggable = createDraggable({id: 'draggable'});
  const droppable = createDroppable({id: 'droppable'});
</script>

<DragDropProvider {onDragEnd}>
  <div class="container">
    {#if parent == null}
      <button {@attach draggable.attach} class="draggable">Drag me</button>
    {/if}
    <div {@attach droppable.attach} class="droppable" class:active={droppable.isDropTarget}>
      {#if parent === 'droppable'}
        <button {@attach draggable.attach} class="draggable">Drag me</button>
      {:else}
        Drop here
      {/if}
    </div>
  </div>
</DragDropProvider>

// apps/templates/react-draggable/src/App.jsx
import { useState } from 'react';
import { DragDropProvider, useDraggable, useDroppable } from '@dnd-kit/react';

function Draggable() {
  const { ref } = useDraggable({ id: 'draggable' });

  return (
    <button ref={ref} className="draggable">
      Drag me
    </button>
  );
}

function Droppable({ children }) {
  const { isDropTarget, ref } = useDroppable({ id: 'droppable' });

  return (
    <div ref={ref} className={`droppable ${isDropTarget ? 'active' : ''}`}>
      {children || 'Drop here'}
    </div>
  );
}

export default function App() {
  const [parent, setParent] = useState(undefined);

  return (
    <DragDropProvider
      onDragEnd={(event) => {
        if (event.canceled) return;
        setParent(event.operation.target?.id);
      }}
    >
      <div className="container">
        {parent == null ? <Draggable /> : null}
        <Droppable>
          {parent === 'droppable' ? <Draggable /> : null}
        </Droppable>
      </div>
    </DragDropProvider>
  );
}
