// packages/react/src/core/context/DragDropProvider.tsx
import {
  startTransition,
  useEffect,
  useState,
  type PropsWithChildren,
} from 'react';
import type {DragDropEvents} from '@dnd-kit/abstract';
import {DragDropManager, defaultPreset} from '@dnd-kit/dom';
import type {DragDropManagerInput, Draggable, Droppable} from '@dnd-kit/dom';
import {useLatest, useOnValueChange} from '@dnd-kit/react/hooks';

import {DragDropContext} from './context.ts';
import {useRenderer} from './renderer.ts';

type Events = DragDropEvents<Draggable, Droppable, DragDropManager>;

export interface Props extends DragDropManagerInput, PropsWithChildren {
  manager?: DragDropManager;
  onBeforeDragStart?: Events['beforedragstart'];
  onCollision?: Events['collision'];
  onDragStart?: Events['dragstart'];
  onDragMove?: Events['dragmove'];
  onDragOver?: Events['dragover'];
  onDragEnd?: Events['dragend'];
}

export function DragDropProvider({
  children,
  onCollision,
  onBeforeDragStart,
  onDragStart,
  onDragMove,
  onDragOver,
  onDragEnd,
  ...input
}: Props) {
  const {renderer, trackRendering} = useRenderer();
  const [manager, setManager] = useState<DragDropManager | null>(
    input.manager ?? null
  );
  const {plugins, modifiers, sensors} = input;
  const handleBeforeDragStart = useLatest(onBeforeDragStart);
  const handleDragStart = useLatest(onDragStart);
  const handleDragOver = useLatest(onDragOver);
  const handleDragMove = useLatest(onDragMove);
  const handleDragEnd = useLatest(onDragEnd);
  const handleCollision = useLatest(onCollision);

  useEffect(() => {
    const manager = input.manager ?? new DragDropManager(input);
    manager.renderer = renderer;

    manager.monitor.addEventListener('beforedragstart', (event, manager) => {
      const callback = handleBeforeDragStart.current;

      if (callback) {
        trackRendering(() => callback(event, manager));
      }
    });
    manager.monitor.addEventListener('dragstart', (event, manager) =>
      handleDragStart.current?.(event, manager)
    );
    manager.monitor.addEventListener('dragover', (event, manager) => {
      const callback = handleDragOver.current;

      if (callback) {
        trackRendering(() => callback(event, manager));
      }
    });
    manager.monitor.addEventListener('dragmove', (event, manager) => {
      const callback = handleDragMove.current;

      if (callback) {
        trackRendering(() => callback(event, manager));
      }
    });
    manager.monitor.addEventListener('dragend', (event, manager) => {
      const callback = handleDragEnd.current;

      if (callback) {
        trackRendering(() => callback(event, manager));
      }
    });
    manager.monitor.addEventListener('collision', (event, manager) =>
      handleCollision.current?.(event, manager)
    );

    startTransition(() => setManager(manager));

    return manager.destroy;
  }, [renderer, input.manager]);

  useOnValueChange(
    plugins,
    () => manager && (manager.plugins = plugins ?? defaultPreset.plugins)
  );
  useOnValueChange(
    sensors,
    () => manager && (manager.sensors = sensors ?? defaultPreset.sensors)
  );
  useOnValueChange(
    modifiers,
    () => manager && (manager.modifiers = modifiers ?? [])
  );

  return (
    <DragDropContext.Provider value={manager}>
      {children}
    </DragDropContext.Provider>
  );
}

// packages/svelte/src/core/context/DragDropProvider.svelte
<script lang="ts">
  import type {Snippet} from 'svelte';
  import {onDestroy} from 'svelte';
  import type {DragDropEventHandlers} from '@dnd-kit/abstract';
  import {
    DragDropManager,
    defaultPreset,
    resolveCustomizable,
    type DragDropManagerInput,
    type Draggable,
    type Droppable,
  } from '@dnd-kit/dom';

  import {createRenderer} from './renderer.svelte.js';
  import {setDragDropContext} from './context.js';

  type Events = DragDropEventHandlers<Draggable, Droppable, DragDropManager>;

  interface Props extends DragDropManagerInput {
    manager?: DragDropManager;
    children?: Snippet;
    onBeforeDragStart?: Events['beforedragstart'];
    onDragStart?: Events['dragstart'];
    onDragMove?: Events['dragmove'];
    onDragOver?: Events['dragover'];
    onDragEnd?: Events['dragend'];
    onCollision?: Events['collision'];
  }

  let {
    manager: managerProp,
    plugins,
    sensors,
    modifiers,
    children,
    onBeforeDragStart,
    onDragStart,
    onDragMove,
    onDragOver,
    onDragEnd,
    onCollision,
  }: Props = $props();

  const {renderer, trackRendering} = createRenderer();

  const manager =
    managerProp ?? new DragDropManager({plugins, sensors, modifiers});

  manager.renderer = renderer;

  setDragDropContext(manager);

  $effect(() => {
    manager.plugins = resolveCustomizable(plugins, defaultPreset.plugins);
    manager.sensors = resolveCustomizable(sensors, defaultPreset.sensors);
    manager.modifiers = resolveCustomizable(modifiers, defaultPreset.modifiers);
  });

  $effect(() => {
    const cleanupFns: (() => void)[] = [];

    cleanupFns.push(
      manager.monitor.addEventListener('beforedragstart', (event, mgr) =>
        trackRendering(() => onBeforeDragStart?.(event, mgr))
      )
    );

    cleanupFns.push(
      manager.monitor.addEventListener('dragstart', (event, mgr) =>
        onDragStart?.(event, mgr)
      )
    );

    cleanupFns.push(
      manager.monitor.addEventListener('dragover', (event, mgr) =>
        trackRendering(() => onDragOver?.(event, mgr))
      )
    );

    cleanupFns.push(
      manager.monitor.addEventListener('dragmove', (event, mgr) =>
        trackRendering(() => onDragMove?.(event, mgr))
      )
    );

    cleanupFns.push(
      manager.monitor.addEventListener('dragend', (event, mgr) =>
        trackRendering(() => onDragEnd?.(event, mgr))
      )
    );

    cleanupFns.push(
      manager.monitor.addEventListener('collision', (event, mgr) =>
        onCollision?.(event, mgr)
      )
    );

    return () => cleanupFns.forEach((fn) => fn());
  });

  onDestroy(() => {
    if (!managerProp) {
      manager.destroy();
    }
  });
</script>

{@render children?.()}
