// apps/stories-solid/components/Button/Button.tsx
import styles from './Button.module.css';

import { JSX } from 'solid-js';
import { classNames } from '@/utilities';

export function Button(props: JSX.ButtonHTMLAttributes<HTMLButtonElement> & { shadow?: boolean }) {
  return (
    <button 
      {...props} 
      class={classNames(styles.Button, props.class)}
      data-shadow={props.shadow}
    >
      {props.children}
    </button>
  );
}

// stories/components/Button/Button.tsx
import React, {HTMLAttributes} from 'react';
import classNames from 'classnames';

import styles from './Button.module.css';

export interface Props extends HTMLAttributes<HTMLButtonElement> {
  children: React.ReactNode;
}

export function Button({children, ...props}: Props) {
  return (
    <button className={classNames(styles.Button)} {...props}>
      {children}
    </button>
  );
}
