// apps/stories-solid/stories/Draggable/DraggableExample.tsx
import {DragDropProvider, useDraggable} from '@dnd-kit/solid';
import draggableIconSrc from '@dnd-kit/stories-shared/assets/draggableIcon.svg';

function DraggableItem() {
  const {isDragging, ref} = useDraggable({id: 'draggable'});

  return (
    <button-component ref={ref} data-shadow={isDragging}>
      <img src={draggableIconSrc} alt="Draggable" width={140} draggable={false} style={{"pointer-events": 'none'}} />
    </button-component>
  );
}

export function DraggableExample() {
  return (
    <DragDropProvider>
      <div>
        <DraggableItem />
      </div>
    </DragDropProvider>
  );
}

// apps/stories-vue/stories/Draggable/DraggableExample.vue
<script setup lang="ts">
import {ref} from 'vue';
import {DragDropProvider, useDraggable} from '@dnd-kit/vue';
import draggableIconSrc from '@dnd-kit/stories-shared/assets/draggableIcon.svg';

const element = ref<HTMLElement | null>(null);
const {isDragging} = useDraggable({id: 'draggable', element});
</script>

<template>
  <DragDropProvider>
    <div>
      <button-component ref="element" :data-shadow="isDragging">
        <img :src="draggableIconSrc" alt="Draggable" :width="140" draggable="false" style="pointer-events: none" />
      </button-component>
    </div>
  </DragDropProvider>
</template>
