// packages/solid/src/core/draggable/useDraggable.ts
import type {Data} from '@dnd-kit/abstract';
import type {DraggableInput} from '@dnd-kit/dom';
import {Draggable} from '@dnd-kit/dom';
import {createEffect, createSignal} from 'solid-js';

import {useDeepSignal} from '../../hooks/useDeepSignal.ts';
import {useInstance} from '../hooks/useInstance.ts';

export interface UseDraggableInput<T extends Data = Data>
  extends Omit<DraggableInput<T>, 'handle' | 'element'> {
  handle?: Element;
  element?: Element;
}

export function useDraggable<T extends Data = Data>(
  input: UseDraggableInput<T>
) {
  const draggable = useInstance(
    (manager) =>
      new Draggable(
        {
          ...input,
          register: false,
          element: input.element,
          handle: input.handle,
        },
        manager
      )
  );
  const trackedDraggable = useDeepSignal(() => draggable);

  const [element, setElement] = createSignal<Element | undefined>(
    input.element
  );
  const [handle, setHandle] = createSignal<Element | undefined>(input.handle);

  createEffect(() => {
    const el = element();
    if (el) draggable.element = el;

    const h = handle();
    if (h) draggable.handle = h;

    draggable.id = input.id;
    draggable.disabled = input.disabled ?? false;
    draggable.feedback = input.feedback ?? 'default';
    draggable.alignment = input.alignment;
    draggable.modifiers = input.modifiers;
    draggable.sensors = input.sensors;

    if (input.data) {
      draggable.data = input.data;
    }
  });

  return {
    get draggable() {
      return draggable;
    },
    isDragging: () => trackedDraggable().isDragging,
    isDropping: () => trackedDraggable().isDropping,
    isDragSource: () => trackedDraggable().isDragSource,
    ref: setElement,
    handleRef: setHandle,
  };
}

// packages/react/src/draggable/useDraggable.ts
import {useCallback, useEffect} from 'react';
import type {Data} from '@dnd-kit/abstract';
import {CloneFeedback, Draggable} from '@dnd-kit/dom';
import type {DraggableInput} from '@dnd-kit/dom';

import {useDragDropManager} from '../context';
import {
  useComputed,
  useConstant,
  useIsomorphicLayoutEffect,
  useOnValueChange,
} from '../hooks';
import {getCurrentValue, type RefOrValue} from '../utilities';

export interface UseDraggableInput<T extends Data = Data>
  extends Omit<DraggableInput<T>, 'activator' | 'element'> {
  activator?: RefOrValue<Element>;
  element?: RefOrValue<Element>;
}

export function useDraggable<T extends Data = Data>(
  input: UseDraggableInput<T>
) {
  const manager = useDragDropManager();
  const {disabled, id, sensors, feedback = CloneFeedback} = input;
  const activator = getCurrentValue(input.activator);
  const element = getCurrentValue(input.element);
  const draggable = useConstant(
    () => new Draggable({...input, activator, element, feedback: null}, manager)
  );
  const isDragSource = useComputed(() => draggable.isDragSource).value;

  useOnValueChange(id, () => (draggable.id = id));
  useOnValueChange(activator, () => (draggable.activator = activator));
  useOnValueChange(element, () => (draggable.element = element));
  useOnValueChange(disabled, () => (draggable.disabled = disabled === true));
  useOnValueChange(sensors, () => (draggable.sensors = sensors));

  useIsomorphicLayoutEffect(() => {
    // Wait until React has had a chance to re-render before updating the feedback
    draggable.feedback = isDragSource ? feedback ?? null : null;
  }, [isDragSource]);

  useEffect(() => {
    // Cleanup on unmount
    return draggable.destroy;
  }, [draggable]);

  return {
    isDragSource,
    ref: useCallback(
      (element: Element | null) => {
        draggable.element = element ?? undefined;
      },
      [draggable]
    ),
  };
}
