// apps/docs/stories/components/Button/Button.tsx
import React, {
  forwardRef,
  type HTMLAttributes,
  type PropsWithChildren,
} from 'react';

import {classNames} from '../../utilities';

import styles from './Button.module.css';

export interface Props extends HTMLAttributes<HTMLButtonElement> {
  shadow?: boolean;
}

export const Button = forwardRef<HTMLButtonElement, PropsWithChildren<Props>>(
  function Button({children, shadow, ...props}, ref) {
    return (
      <button
        {...props}
        className={classNames(styles.Button, shadow && styles.shadow)}
        ref={ref}
      >
        {children}
      </button>
    );
  }
);

// apps/stories-solid/components/Button/Button.tsx
import styles from './Button.module.css';

import { JSX } from 'solid-js';
import { classNames } from '@/utilities';

export function Button(props: JSX.ButtonHTMLAttributes<HTMLButtonElement> & { shadow?: boolean }) {
  return (
    <button 
      {...props} 
      class={classNames(styles.Button, props.class)}
      data-shadow={props.shadow}
    >
      {props.children}
    </button>
  );
}
