// packages/solid/src/core/draggable/DragOverlay.tsx
import {Feedback} from '@dnd-kit/dom';
import {Show, createEffect, createMemo, createSignal, onCleanup} from 'solid-js';
import {Dynamic} from 'solid-js/web';

import {DragDropContext} from '../context/context.ts';
import {useDragDropManager} from '../hooks/useDragDropManager.ts';
import {useDragOperation} from '../hooks/useDragOperation.ts';

import type {DragDropManager, Draggable, Droppable, DropAnimation} from '@dnd-kit/dom';
import type {JSX, ValidComponent} from 'solid-js';
import type {Data} from '@dnd-kit/abstract';

export interface DragOverlayProps<
  T extends Data,
  U extends Draggable<T>,
> {
  class?: string;
  children: JSX.Element | ((source: U) => JSX.Element);
  /**
   * Customize or disable the drop animation that plays when a drag operation ends.
   *
   * - `undefined` – use the default animation (250ms ease)
   * - `null` – disable the drop animation entirely
   * - `{duration, easing}` – customize the animation timing
   * - `(context) => Promise<void> | void` – provide a fully custom animation function
   */
  dropAnimation?: DropAnimation | null;
  style?: JSX.CSSProperties;
  tag?: ValidComponent;
  disabled?: boolean | ((source: U | null) => boolean);
}

export function DragOverlay<T extends Data, U extends Draggable<T>>(
  props: DragOverlayProps<T, U>
) {
  const [element, setElement] = createSignal<HTMLElement>();
  const manager = useDragDropManager();
  const patchedManager = createPatchedManager(() => manager);
  const dragOperation = useDragOperation();

  const source = () => dragOperation.source() as U | null;

  const isDisabled = () => {
    if (typeof props.disabled === 'function') {
      return props.disabled(source());
    }
    return props.disabled ?? false;
  };

  createEffect(() => {
    if (!source()) {
      setElement(undefined);
    }
  });

  createEffect(() => {
    const _manager = manager;

    if (!_manager || isDisabled()) return;

    const feedback = _manager.plugins.find(
      (plugin): plugin is Feedback => plugin instanceof Feedback
    );

    if (!feedback) return;

    feedback.overlay = element();
    feedback.dropAnimation = props.dropAnimation;

    onCleanup(() => {
      feedback.overlay = undefined;
      feedback.dropAnimation = undefined;
    });
  });

  return (
    <DragDropContext.Provider value={patchedManager()}>
      <Show when={!isDisabled() ? source() : undefined}>
        {(src) => (
          <Dynamic
            component={props.tag || 'div'}
            class={props.class}
            style={props.style}
            data-dnd-overlay
            ref={setElement}
          >
            {typeof props.children === 'function'
              ? props.children(src() as unknown as U)
              : props.children}
          </Dynamic>
        )}
      </Show>
    </DragDropContext.Provider>
  );
}

function createPatchedManager<
  T extends Data,
  U extends Draggable<T>,
  V extends Droppable<T>,
  W extends DragDropManager<T, U, V>,
>(manager: () => W | null) {
  return createMemo(() => {
    const _manager = manager();

    if (!_manager) return null;

    const patchedRegistry = new Proxy(_manager.registry, {
      get(target, property) {
        if (property === 'register' || property === 'unregister') {
          return noop;
        }
        return target[property as keyof typeof target];
      },
    });

    return new Proxy(_manager, {
      get(target, property) {
        if (property === 'registry') {
          return patchedRegistry;
        }
        return target[property as keyof typeof target];
      },
    });
  });
}

function noop() {
  return () => {};
}

// packages/react/src/core/draggable/DragOverlay.tsx
import {createElement, useEffect, useMemo, useRef, type ReactNode} from 'react';
import {useComputed, useDeepSignal} from '@dnd-kit/react/hooks';
import {DragDropManager, Draggable, Feedback} from '@dnd-kit/dom';
import type {DropAnimation} from '@dnd-kit/dom';
import {Data} from '@dnd-kit/abstract';

import {useDragDropManager} from '../hooks/useDragDropManager.ts';
import {DragDropContext} from '../context/context.ts';

export interface Props<T extends Data, U extends Draggable<T>> {
  className?: string;
  children: ReactNode | ((source: U) => ReactNode);
  /**
   * Customize or disable the drop animation that plays when a drag operation ends.
   *
   * - `undefined` – use the default animation (250ms ease)
   * - `null` – disable the drop animation entirely
   * - `{duration, easing}` – customize the animation timing
   * - `(context) => Promise<void> | void` – provide a fully custom animation function
   */
  dropAnimation?: DropAnimation | null;
  style?: React.CSSProperties;
  tag?: string;
  disabled?: boolean | ((source: U | null) => boolean);
}

export function DragOverlay<T extends Data, U extends Draggable<T>>({
  children,
  className,
  dropAnimation,
  style,
  tag,
  disabled,
}: Props<T, U>) {
  const ref = useRef<HTMLDivElement | null>(null);
  const manager = useDragDropManager<T, U>();
  const source =
    useComputed(() => manager?.dragOperation.source, [manager]).value ?? null;
  const isDisabled =
    typeof disabled === 'function' ? disabled(source) : disabled;

  useEffect(() => {
    if (!ref.current || !manager || isDisabled) return;

    const feedback = manager.plugins.find(
      (plugin) => plugin instanceof Feedback
    );

    if (!feedback) return;

    feedback.overlay = ref.current;

    return () => {
      feedback.overlay = undefined;
    };
  }, [manager, isDisabled]);

  useEffect(() => {
    if (!manager) return;

    const feedback = manager.plugins.find(
      (plugin) => plugin instanceof Feedback
    );

    if (!feedback) return;

    feedback.dropAnimation = dropAnimation;

    return () => {
      feedback.dropAnimation = undefined;
    };
  }, [manager, dropAnimation]);

  // Prevent children of the overlay from registering themselves as draggables or droppables
  const patchedManager = useMemo(() => {
    if (!manager) return null;

    const patchedRegistry = new Proxy(manager.registry, {
      get(target, property) {
        if (property === 'register' || property === 'unregister') {
          return noop;
        }

        return target[property as keyof typeof target];
      },
    });

    return new Proxy(manager, {
      get(target, property) {
        if (property === 'registry') {
          return patchedRegistry;
        }

        return target[property as keyof typeof target];
      },
    });
  }, [manager]);

  return (
    <DragDropContext.Provider value={patchedManager as DragDropManager | null}>
      {createElement(
        tag || 'div',
        {ref, className, style, 'data-dnd-overlay': true},

        renderChildren()
      )}
    </DragDropContext.Provider>
  );

  function renderChildren() {
    if (!source || isDisabled) return null;

    if (typeof children === 'function') {
      return <Children source={source}>{children}</Children>;
    }

    return children;
  }
}

function noop() {
  return () => {};
}

function Children<T extends Data, U extends Draggable<T>>({
  children,
  source,
}: {
  children: (source: U) => ReactNode;
  source: U;
}) {
  return children(useDeepSignal(source));
}
