// packages/svelte/src/core/draggable/DragOverlay.svelte
<script lang="ts">
  import type {Snippet} from 'svelte';
  import type {DragDropManager, Draggable, DropAnimation} from '@dnd-kit/dom';
  import {Feedback} from '@dnd-kit/dom';

  import {useDeepSignal} from '../../hooks/useDeepSignal.svelte.js';
  import {getDragDropManager} from '../hooks/getDragDropManager.js';
  import {DND_CONTEXT_KEY, setDragDropContext} from '../context/context.js';

  interface Props {
    /**
     * Whether the drag overlay is disabled.
     */
    disabled?: boolean;
    /**
     * Customize or disable the drop animation that plays when a drag operation ends.
     *
     * - `undefined` – use the default animation (250ms ease)
     * - `null` – disable the drop animation entirely
     * - `{duration, easing}` – customize the animation timing
     * - `(context) => Promise<void> | void` – provide a fully custom animation function
     */
    dropAnimation?: DropAnimation | null;
    /**
     * Content to render inside the overlay.
     * Receives the drag source as a snippet parameter.
     */
    children?: Snippet<[Draggable]>;
  }

  let {disabled = false, dropAnimation, children}: Props = $props();

  const manager = getDragDropManager();
  let overlayElement = $state<HTMLElement | null>(null);

  const trackedDragOperation = useDeepSignal(() => manager.dragOperation);

  // Provide a patched manager that prevents children from registering
  const noop = () => () => {};

  const patchedRegistry = new Proxy(manager.registry, {
    get(target, property) {
      if (property === 'register' || property === 'unregister') {
        return noop;
      }

      return target[property as keyof typeof target];
    },
  });

  const patchedManager = new Proxy(manager, {
    get(target, property) {
      if (property === 'registry') {
        return patchedRegistry;
      }

      return target[property as keyof typeof target];
    },
  }) as DragDropManager;

  setDragDropContext(patchedManager);

  // Register overlay element and dropAnimation with the Feedback plugin
  $effect(() => {
    const el = overlayElement;
    if (!el || disabled) return;

    const feedback = manager.plugins.find(
      (plugin): plugin is Feedback => plugin instanceof Feedback
    );

    if (!feedback) return;

    feedback.overlay = el;
    feedback.dropAnimation = dropAnimation;

    return () => {
      feedback.overlay = undefined;
      feedback.dropAnimation = undefined;
    };
  });
</script>

<div bind:this={overlayElement} data-dnd-overlay>
  {#if !disabled && trackedDragOperation.current.source}
    {@render children?.(trackedDragOperation.current.source)}
  {/if}
</div>

// packages/react/src/core/draggable/DragOverlay.tsx
import {createElement, useEffect, useMemo, useRef, type ReactNode} from 'react';
import {useComputed, useDeepSignal} from '@dnd-kit/react/hooks';
import {DragDropManager, Draggable, Feedback} from '@dnd-kit/dom';
import type {DropAnimation} from '@dnd-kit/dom';
import {Data} from '@dnd-kit/abstract';

import {useDragDropManager} from '../hooks/useDragDropManager.ts';
import {DragDropContext} from '../context/context.ts';

export interface Props<T extends Data, U extends Draggable<T>> {
  className?: string;
  children: ReactNode | ((source: U) => ReactNode);
  /**
   * Customize or disable the drop animation that plays when a drag operation ends.
   *
   * - `undefined` – use the default animation (250ms ease)
   * - `null` – disable the drop animation entirely
   * - `{duration, easing}` – customize the animation timing
   * - `(context) => Promise<void> | void` – provide a fully custom animation function
   */
  dropAnimation?: DropAnimation | null;
  style?: React.CSSProperties;
  tag?: string;
  disabled?: boolean | ((source: U | null) => boolean);
}

export function DragOverlay<T extends Data, U extends Draggable<T>>({
  children,
  className,
  dropAnimation,
  style,
  tag,
  disabled,
}: Props<T, U>) {
  const ref = useRef<HTMLDivElement | null>(null);
  const manager = useDragDropManager<T, U>();
  const source =
    useComputed(() => manager?.dragOperation.source, [manager]).value ?? null;
  const isDisabled =
    typeof disabled === 'function' ? disabled(source) : disabled;

  useEffect(() => {
    if (!ref.current || !manager || isDisabled) return;

    const feedback = manager.plugins.find(
      (plugin) => plugin instanceof Feedback
    );

    if (!feedback) return;

    feedback.overlay = ref.current;

    return () => {
      feedback.overlay = undefined;
    };
  }, [manager, isDisabled]);

  useEffect(() => {
    if (!manager) return;

    const feedback = manager.plugins.find(
      (plugin) => plugin instanceof Feedback
    );

    if (!feedback) return;

    feedback.dropAnimation = dropAnimation;

    return () => {
      feedback.dropAnimation = undefined;
    };
  }, [manager, dropAnimation]);

  // Prevent children of the overlay from registering themselves as draggables or droppables
  const patchedManager = useMemo(() => {
    if (!manager) return null;

    const patchedRegistry = new Proxy(manager.registry, {
      get(target, property) {
        if (property === 'register' || property === 'unregister') {
          return noop;
        }

        return target[property as keyof typeof target];
      },
    });

    return new Proxy(manager, {
      get(target, property) {
        if (property === 'registry') {
          return patchedRegistry;
        }

        return target[property as keyof typeof target];
      },
    });
  }, [manager]);

  return (
    <DragDropContext.Provider value={patchedManager as DragDropManager | null}>
      {createElement(
        tag || 'div',
        {ref, className, style, 'data-dnd-overlay': true},

        renderChildren()
      )}
    </DragDropContext.Provider>
  );

  function renderChildren() {
    if (!source || isDisabled) return null;

    if (typeof children === 'function') {
      return <Children source={source}>{children}</Children>;
    }

    return children;
  }
}

function noop() {
  return () => {};
}

function Children<T extends Data, U extends Draggable<T>>({
  children,
  source,
}: {
  children: (source: U) => ReactNode;
  source: U;
}) {
  return children(useDeepSignal(source));
}
